<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function players_games_theme($existing, $type, $theme, $path) {
  return [
    'players_waitlist' => [
      'variables' => [
        'games' => NULL,
      ],
    ],
  ];
}


function players_games_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (
    $form_id == 'node_players_games_form' ||
    $form_id == 'node_players_games_edit_form'
  ) {
    $form['field_players_games']['#states'] = [
      'invisible' => [
        ':input[name="field_players_game_date[0][value][date]"]' => ['value' => ''],
      ],
    ];
  }
}
